import { createSchema } from "@ponder/core";

export default createSchema((p) => ({
  srcEscrow: p.createTable({
    id: p.string(),
    chainId: p.int(),
    escrowAddress: p.hex(),
    orderHash: p.hex(),
    hashlock: p.hex(),
    maker: p.hex(),
    taker: p.hex(),
    srcToken: p.hex(),
    srcAmount: p.bigint(),
    srcSafetyDeposit: p.bigint(),
    dstMaker: p.hex(),
    dstToken: p.hex(),
    dstAmount: p.bigint(),
    dstSafetyDeposit: p.bigint(),
    dstChainId: p.bigint(),
    timelocks: p.bigint(),
    createdAt: p.bigint(),
    blockNumber: p.bigint(),
    transactionHash: p.hex(),
    status: p.string(),
  }),

  dstEscrow: p.createTable({
    id: p.string(),
    chainId: p.int(),
    escrowAddress: p.hex(),
    hashlock: p.hex(),
    taker: p.hex(),
    srcCancellationTimestamp: p.bigint(),
    createdAt: p.bigint(),
    blockNumber: p.bigint(),
    transactionHash: p.hex(),
    status: p.string(),
  }),

  escrowWithdrawal: p.createTable({
    id: p.string(),
    chainId: p.int(),
    escrowAddress: p.hex(),
    secret: p.hex(),
    withdrawnAt: p.bigint(),
    blockNumber: p.bigint(),
    transactionHash: p.hex(),
  }),

  escrowCancellation: p.createTable({
    id: p.string(),
    chainId: p.int(),
    escrowAddress: p.hex(),
    cancelledAt: p.bigint(),
    blockNumber: p.bigint(),
    transactionHash: p.hex(),
  }),

  fundsRescued: p.createTable({
    id: p.string(),
    chainId: p.int(),
    escrowAddress: p.hex(),
    token: p.hex(),
    amount: p.bigint(),
    rescuedAt: p.bigint(),
    blockNumber: p.bigint(),
    transactionHash: p.hex(),
    logIndex: p.int(),
  }),

  atomicSwap: p.createTable({
    id: p.string(),
    orderHash: p.hex(),
    hashlock: p.hex(),
    srcChainId: p.int(),
    dstChainId: p.int(),
    srcEscrowAddress: p.hex().optional(),
    dstEscrowAddress: p.hex().optional(),
    srcMaker: p.hex(),
    srcTaker: p.hex(),
    dstMaker: p.hex(),
    dstTaker: p.hex(),
    srcToken: p.hex(),
    srcAmount: p.bigint(),
    dstToken: p.hex(),
    dstAmount: p.bigint(),
    srcSafetyDeposit: p.bigint(),
    dstSafetyDeposit: p.bigint(),
    timelocks: p.bigint(),
    status: p.string(),
    srcCreatedAt: p.bigint().optional(),
    dstCreatedAt: p.bigint().optional(),
    completedAt: p.bigint().optional(),
    cancelledAt: p.bigint().optional(),
    secret: p.hex().optional(),
  }),

  chainStatistics: p.createTable({
    id: p.string(),
    chainId: p.int(),
    totalSrcEscrows: p.bigint(),
    totalDstEscrows: p.bigint(),
    totalWithdrawals: p.bigint(),
    totalCancellations: p.bigint(),
    totalVolumeLocked: p.bigint(),
    totalVolumeWithdrawn: p.bigint(),
    lastUpdatedBlock: p.bigint(),
  }),
}));